//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ask.UI.Resources.Localization.Language {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ask.UI.Resources.Localization.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шина A.
        /// </summary>
        internal static string input_bus_a {
            get {
                return ResourceManager.GetString("input.bus.a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шина B.
        /// </summary>
        internal static string input_bus_b {
            get {
                return ResourceManager.GetString("input.bus.b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A1B1.
        /// </summary>
        internal static string input_bus_group_ab1 {
            get {
                return ResourceManager.GetString("input.bus.group.ab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A2B2.
        /// </summary>
        internal static string input_bus_group_ab2 {
            get {
                return ResourceManager.GetString("input.bus.group.ab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A3B3.
        /// </summary>
        internal static string input_bus_group_ab3 {
            get {
                return ResourceManager.GetString("input.bus.group.ab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A4B4.
        /// </summary>
        internal static string input_bus_group_ab4 {
            get {
                return ResourceManager.GetString("input.bus.group.ab4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа шин.
        /// </summary>
        internal static string input_bus_group_title {
            get {
                return ResourceManager.GetString("input.bus.group.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шина для проверки.
        /// </summary>
        internal static string input_bus_title {
            get {
                return ResourceManager.GetString("input.bus.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электрический параметр.
        /// </summary>
        internal static string input_electrical_title {
            get {
                return ResourceManager.GetString("input.electrical.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальная точка a.b.c.
        /// </summary>
        internal static string input_first_title {
            get {
                return ResourceManager.GetString("input.first.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите значение....
        /// </summary>
        internal static string input_placeholder {
            get {
                return ResourceManager.GetString("input.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конечная точка a.b.c.
        /// </summary>
        internal static string input_second_title {
            get {
                return ResourceManager.GetString("input.second.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на от 1 до 999 сек..
        /// </summary>
        internal static string input_time_placeholder {
            get {
                return ResourceManager.GetString("input.time.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время выполнения в сек..
        /// </summary>
        internal static string input_time_title {
            get {
                return ResourceManager.GetString("input.time.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время нарастания в сек..
        /// </summary>
        internal static string input_timeramp_title {
            get {
                return ResourceManager.GetString("input.timeramp.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напряжение в В..
        /// </summary>
        internal static string input_voltage_title {
            get {
                return ResourceManager.GetString("input.voltage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        internal static string menu_admin {
            get {
                return ResourceManager.GetString("menu.admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение.
        /// </summary>
        internal static string menu_execution {
            get {
                return ResourceManager.GetString("menu.execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трансляции.
        /// </summary>
        internal static string menu_execution_build {
            get {
                return ResourceManager.GetString("menu.execution.build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск.
        /// </summary>
        internal static string menu_execution_run {
            get {
                return ResourceManager.GetString("menu.execution.run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск (Пошаговый режим).
        /// </summary>
        internal static string menu_execution_run_stepByStepMode {
            get {
                return ResourceManager.GetString("menu.execution.run.stepByStepMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        internal static string menu_file {
            get {
                return ResourceManager.GetString("menu.file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архив.
        /// </summary>
        internal static string menu_file_archive {
            get {
                return ResourceManager.GetString("menu.file.archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сравнить.
        /// </summary>
        internal static string menu_file_compare {
            get {
                return ResourceManager.GetString("menu.file.compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string menu_file_exit {
            get {
                return ResourceManager.GetString("menu.file.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        internal static string menu_file_new {
            get {
                return ResourceManager.GetString("menu.file.new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        internal static string menu_file_open {
            get {
                return ResourceManager.GetString("menu.file.open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть папку в проводнике.
        /// </summary>
        internal static string menu_file_openfolder {
            get {
                return ResourceManager.GetString("menu.file.openfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать.
        /// </summary>
        internal static string menu_file_print {
            get {
                return ResourceManager.GetString("menu.file.print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string menu_file_save {
            get {
                return ResourceManager.GetString("menu.file.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить как.
        /// </summary>
        internal static string menu_file_saveas {
            get {
                return ResourceManager.GetString("menu.file.saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск и замена.
        /// </summary>
        internal static string menu_file_search {
            get {
                return ResourceManager.GetString("menu.file.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        internal static string menu_help {
            get {
                return ResourceManager.GetString("menu.help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string menu_help_aboutProgram {
            get {
                return ResourceManager.GetString("menu.help.aboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список команд.
        /// </summary>
        internal static string menu_help_fastMenuCommand {
            get {
                return ResourceManager.GetString("menu.help.fastMenuCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общие сведения.
        /// </summary>
        internal static string menu_help_generalInformation {
            get {
                return ResourceManager.GetString("menu.help.generalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык программ контроля.
        /// </summary>
        internal static string menu_help_languageControlPrograms {
            get {
                return ResourceManager.GetString("menu.help.languageControlPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состав программы.
        /// </summary>
        internal static string menu_help_programComposition {
            get {
                return ResourceManager.GetString("menu.help.programComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string menu_settings {
            get {
                return ResourceManager.GetString("menu.settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация.
        /// </summary>
        internal static string menu_settings_configuration {
            get {
                return ResourceManager.GetString("menu.settings.configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение.
        /// </summary>
        internal static string menu_settings_execution {
            get {
                return ResourceManager.GetString("menu.settings.execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол.
        /// </summary>
        internal static string menu_settings_protocol {
            get {
                return ResourceManager.GetString("menu.settings.protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испытания.
        /// </summary>
        internal static string menu_test {
            get {
                return ResourceManager.GetString("menu.test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метрология.
        /// </summary>
        internal static string menu_test_metrology {
            get {
                return ResourceManager.GetString("menu.test.metrology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим СИ.
        /// </summary>
        internal static string menu_test_metrology_ci {
            get {
                return ResourceManager.GetString("menu.test.metrology.ci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ЭТ.
        /// </summary>
        internal static string menu_test_metrology_eht {
            get {
                return ResourceManager.GetString("menu.test.metrology.eht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ИЕ.
        /// </summary>
        internal static string menu_test_metrology_ie {
            get {
                return ResourceManager.GetString("menu.test.metrology.ie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим КН (переменный).
        /// </summary>
        internal static string menu_test_metrology_knacw {
            get {
                return ResourceManager.GetString("menu.test.metrology.knacw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим КН (постоянный).
        /// </summary>
        internal static string menu_test_metrology_kndcw {
            get {
                return ResourceManager.GetString("menu.test.metrology.kndcw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим КС.
        /// </summary>
        internal static string menu_test_metrology_ks {
            get {
                return ResourceManager.GetString("menu.test.metrology.ks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ПИ (переменный).
        /// </summary>
        internal static string menu_test_metrology_piacw {
            get {
                return ResourceManager.GetString("menu.test.metrology.piacw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ПИ (постоянный).
        /// </summary>
        internal static string menu_test_metrology_pidcw {
            get {
                return ResourceManager.GetString("menu.test.metrology.pidcw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ПР.
        /// </summary>
        internal static string menu_test_metrology_pr {
            get {
                return ResourceManager.GetString("menu.test.metrology.pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ПР Т.
        /// </summary>
        internal static string menu_test_metrology_prt {
            get {
                return ResourceManager.GetString("menu.test.metrology.prt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самоконтроль.
        /// </summary>
        internal static string menu_test_selfcontrol {
            get {
                return ResourceManager.GetString("menu.test.selfcontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модуль.
        /// </summary>
        internal static string menu_test_selfcontrol_module {
            get {
                return ResourceManager.GetString("menu.test.selfcontrol.module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тесты.
        /// </summary>
        internal static string menu_test_tests {
            get {
                return ResourceManager.GetString("menu.test.tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест СИ.
        /// </summary>
        internal static string menu_test_tests_ci {
            get {
                return ResourceManager.GetString("menu.test.tests.ci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Групповой метод.
        /// </summary>
        internal static string menu_test_tests_ci_group {
            get {
                return ResourceManager.GetString("menu.test.tests.ci.group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод узла.
        /// </summary>
        internal static string menu_test_tests_ci_node {
            get {
                return ResourceManager.GetString("menu.test.tests.ci.node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перекрёстный тест(МКР).
        /// </summary>
        internal static string menu_test_tests_cross_mkr {
            get {
                return ResourceManager.GetString("menu.test.tests.cross.mkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест ПИ на переменном токе.
        /// </summary>
        internal static string menu_test_tests_piacw {
            get {
                return ResourceManager.GetString("menu.test.tests.piacw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Групповой метод.
        /// </summary>
        internal static string menu_test_tests_piacw_group {
            get {
                return ResourceManager.GetString("menu.test.tests.piacw.group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод узла.
        /// </summary>
        internal static string menu_test_tests_piacw_node {
            get {
                return ResourceManager.GetString("menu.test.tests.piacw.node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест ПИ на постоянном токе.
        /// </summary>
        internal static string menu_test_tests_pidcw {
            get {
                return ResourceManager.GetString("menu.test.tests.pidcw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Групповой метод.
        /// </summary>
        internal static string menu_test_tests_pidcw_group {
            get {
                return ResourceManager.GetString("menu.test.tests.pidcw.group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод узла.
        /// </summary>
        internal static string menu_test_tests_pidcw_node {
            get {
                return ResourceManager.GetString("menu.test.tests.pidcw.node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сопротивление коммутатора.
        /// </summary>
        internal static string menu_test_tests_relay_contact_resist_rkomm {
            get {
                return ResourceManager.GetString("menu.test.tests.relay.contact.resist.rkomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОДОЛЖИТЬ(P).
        /// </summary>
        internal static string protocol_button_continue {
            get {
                return ResourceManager.GetString("protocol.button.continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАВЕРШИТЬ(Esc).
        /// </summary>
        internal static string protocol_button_exit {
            get {
                return ResourceManager.GetString("protocol.button.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАЦИКЛИТЬ.
        /// </summary>
        internal static string protocol_button_loop {
            get {
                return ResourceManager.GetString("protocol.button.loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОВТОРИТЬ(R).
        /// </summary>
        internal static string protocol_button_repeat {
            get {
                return ResourceManager.GetString("protocol.button.repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАПУСТИТЬ(F5).
        /// </summary>
        internal static string protocol_button_start {
            get {
                return ResourceManager.GetString("protocol.button.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вглубь(F11).
        /// </summary>
        internal static string protocol_button_stepinto {
            get {
                return ResourceManager.GetString("protocol.button.stepinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поверх(F10).
        /// </summary>
        internal static string protocol_button_stepover {
            get {
                return ResourceManager.GetString("protocol.button.stepover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОСТАНОВИТЬ(P).
        /// </summary>
        internal static string protocol_button_stop {
            get {
                return ResourceManager.GetString("protocol.button.stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название файла.
        /// </summary>
        internal static string protocol_header_file {
            get {
                return ResourceManager.GetString("protocol.header.file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша надпись.
        /// </summary>
        internal static string protocol_header_title {
            get {
                return ResourceManager.GetString("protocol.header.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить (P/F5).
        /// </summary>
        internal static string protocol_tooltip_continue {
            get {
                return ResourceManager.GetString("protocol.tooltip.continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пауза (P/F5).
        /// </summary>
        internal static string protocol_tooltip_pause {
            get {
                return ResourceManager.GetString("protocol.tooltip.pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторить (R).
        /// </summary>
        internal static string protocol_tooltip_repeat {
            get {
                return ResourceManager.GetString("protocol.tooltip.repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить (Enter/F5).
        /// </summary>
        internal static string protocol_tooltip_start {
            get {
                return ResourceManager.GetString("protocol.tooltip.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаг с заходом (F11).
        /// </summary>
        internal static string protocol_tooltip_stepinto {
            get {
                return ResourceManager.GetString("protocol.tooltip.stepinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаг с обходом (F10).
        /// </summary>
        internal static string protocol_tooltip_stepover {
            get {
                return ResourceManager.GetString("protocol.tooltip.stepover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить (Esc).
        /// </summary>
        internal static string protocol_tooltip_stop {
            get {
                return ResourceManager.GetString("protocol.tooltip.stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать.
        /// </summary>
        internal static string settings_config_printButton {
            get {
                return ResourceManager.GetString("settings.config.printButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация АСК.
        /// </summary>
        internal static string settings_config_title {
            get {
                return ResourceManager.GetString("settings.config.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавляет случайные ошибки при холостом режиме для проверки обработки ошибок..
        /// </summary>
        internal static string settings_execution_errorSimulation_description {
            get {
                return ResourceManager.GetString("settings.execution.errorSimulation.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение с ошибками.
        /// </summary>
        internal static string settings_execution_errorSimulation_title {
            get {
                return ResourceManager.GetString("settings.execution.errorSimulation.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает холостой режим выполнения программы, при котором не происходит взаимодействия с оборудованием..
        /// </summary>
        internal static string settings_execution_idleMode_description {
            get {
                return ResourceManager.GetString("settings.execution.idleMode.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Холостой режим выполнения.
        /// </summary>
        internal static string settings_execution_idleMode_title {
            get {
                return ResourceManager.GetString("settings.execution.idleMode.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение.
        /// </summary>
        internal static string settings_execution_section_title {
            get {
                return ResourceManager.GetString("settings.execution.section.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает отладочное выполнение: F10 — выполнить блок целиком (поверх); F11 — заходить в блок и останавливаться на каждом шаге (вглубь)..
        /// </summary>
        internal static string settings_execution_stepByStepMode_description {
            get {
                return ResourceManager.GetString("settings.execution.stepByStepMode.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пошаговый режим.
        /// </summary>
        internal static string settings_execution_stepByStepMode_title {
            get {
                return ResourceManager.GetString("settings.execution.stepByStepMode.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При возникновении ошибки выполнение приостанавливается, чтобы оператор мог осознанно выбрать дальнейшее действие и управлять ходом работы..
        /// </summary>
        internal static string settings_execution_stopOnError_description {
            get {
                return ResourceManager.GetString("settings.execution.stopOnError.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановка по ошибке.
        /// </summary>
        internal static string settings_execution_stopOnError_title {
            get {
                return ResourceManager.GetString("settings.execution.stopOnError.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры.
        /// </summary>
        internal static string settings_main_title {
            get {
                return ResourceManager.GetString("settings.main.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По завершении выполнения отображает диалог выбора принтера для печати итогового протокола..
        /// </summary>
        internal static string settings_protocol_autoPrint_description {
            get {
                return ResourceManager.GetString("settings.protocol.autoPrint.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать протокола.
        /// </summary>
        internal static string settings_protocol_autoPrint_title {
            get {
                return ResourceManager.GetString("settings.protocol.autoPrint.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматически сохраняет протокол каждого запуска. Имя файла содержит дату, время и название выполняемых действий..
        /// </summary>
        internal static string settings_protocol_autoSave_description {
            get {
                return ResourceManager.GetString("settings.protocol.autoSave.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение протокола.
        /// </summary>
        internal static string settings_protocol_autoSave_title {
            get {
                return ResourceManager.GetString("settings.protocol.autoSave.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройка текста протокола для сценариев без ошибок..
        /// </summary>
        internal static string settings_protocol_cleanTextCard_description {
            get {
                return ResourceManager.GetString("settings.protocol.cleanTextCard.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст протокола без ошибок.
        /// </summary>
        internal static string settings_protocol_cleanTextCard_title {
            get {
                return ResourceManager.GetString("settings.protocol.cleanTextCard.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображает информацию о подключении точек и шин на устройствах..
        /// </summary>
        internal static string settings_protocol_deviceInfo_connectionInfo_description {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.connectionInfo.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение точек и шин.
        /// </summary>
        internal static string settings_protocol_deviceInfo_connectionInfo_title {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.connectionInfo.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображает параметры, которые устанавливаются на устройства в ходе выполнения..
        /// </summary>
        internal static string settings_protocol_deviceInfo_deviceExecutionParameters_description {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.deviceExecutionParameters.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры устройств.
        /// </summary>
        internal static string settings_protocol_deviceInfo_deviceExecutionParameters_title {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.deviceExecutionParameters.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройка отображения информации об оборудовании в протоколе выполнения..
        /// </summary>
        internal static string settings_protocol_deviceInfo_group_description {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.group.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация об оборудовании.
        /// </summary>
        internal static string settings_protocol_deviceInfo_group_title {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.group.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображает промежуточные результаты измерений, полученные в ходе выполнения программ контроля..
        /// </summary>
        internal static string settings_protocol_deviceInfo_intermediateMeasurementResults_description {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.intermediateMeasurementResults.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Промежуточные результаты измерений.
        /// </summary>
        internal static string settings_protocol_deviceInfo_intermediateMeasurementResults_title {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.intermediateMeasurementResults.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображение машинных адресов точек системы АСК-МКИ-М..
        /// </summary>
        internal static string settings_protocol_deviceInfo_machineAddresses_description {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.machineAddresses.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машинные адреса.
        /// </summary>
        internal static string settings_protocol_deviceInfo_machineAddresses_title {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.machineAddresses.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображает результаты измерений, полученные в ходе выполнения программ контроля..
        /// </summary>
        internal static string settings_protocol_deviceInfo_measurementResults_description {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.measurementResults.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты измерений.
        /// </summary>
        internal static string settings_protocol_deviceInfo_measurementResults_title {
            get {
                return ResourceManager.GetString("settings.protocol.deviceInfo.measurementResults.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройка текста протокола для сценариев с ошибками..
        /// </summary>
        internal static string settings_protocol_errorTextCard_description {
            get {
                return ResourceManager.GetString("settings.protocol.errorTextCard.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст протокола с ошибками.
        /// </summary>
        internal static string settings_protocol_errorTextCard_title {
            get {
                return ResourceManager.GetString("settings.protocol.errorTextCard.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол будет формироваться после выполнения программ контроля..
        /// </summary>
        internal static string settings_protocol_generate_description {
            get {
                return ResourceManager.GetString("settings.protocol.generate.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формирование протокола.
        /// </summary>
        internal static string settings_protocol_generate_title {
            get {
                return ResourceManager.GetString("settings.protocol.generate.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывает, сколько времени прошло с момента запуска на каждом шаге выполнения..
        /// </summary>
        internal static string settings_protocol_operationTime_description {
            get {
                return ResourceManager.GetString("settings.protocol.operationTime.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывод времени операции.
        /// </summary>
        internal static string settings_protocol_operationTime_title {
            get {
                return ResourceManager.GetString("settings.protocol.operationTime.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол.
        /// </summary>
        internal static string settings_protocol_section_title {
            get {
                return ResourceManager.GetString("settings.protocol.section.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображает краткое описание текущего шага выполнения в виде заголовка..
        /// </summary>
        internal static string settings_protocol_showActionHeaders_description {
            get {
                return ResourceManager.GetString("settings.protocol.showActionHeaders.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображение заголовков действий.
        /// </summary>
        internal static string settings_protocol_showActionHeaders_title {
            get {
                return ResourceManager.GetString("settings.protocol.showActionHeaders.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По завершении выполнения протокол отображается в программном обеспечении, по умолчанию открывается как PDF-файл..
        /// </summary>
        internal static string settings_protocol_showInSoftware_description {
            get {
                return ResourceManager.GetString("settings.protocol.showInSoftware.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывод протокола в ПО.
        /// </summary>
        internal static string settings_protocol_showInSoftware_title {
            get {
                return ResourceManager.GetString("settings.protocol.showInSoftware.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает или отключает фоновое выделение строк проверки цепей и точек в протоколе выполнения..
        /// </summary>
        internal static string settings_userinterface_chainPointBodyBackground_description {
            get {
                return ResourceManager.GetString("settings.userinterface.chainPointBodyBackground.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фоновое выделение цепей и точек.
        /// </summary>
        internal static string settings_userinterface_chainPointBodyBackground_title {
            get {
                return ResourceManager.GetString("settings.userinterface.chainPointBodyBackground.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматически сворачивает завершённые блоки команд в протоколе выполнения. Если отключено, блоки остаются раскрытыми..
        /// </summary>
        internal static string settings_userinterface_commandAutoCollapse_description {
            get {
                return ResourceManager.GetString("settings.userinterface.commandAutoCollapse.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоскрытие блоков в протоколе.
        /// </summary>
        internal static string settings_userinterface_commandAutoCollapse_title {
            get {
                return ResourceManager.GetString("settings.userinterface.commandAutoCollapse.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает или отключает фоновое выделение строк команд в протоколе выполнения..
        /// </summary>
        internal static string settings_userinterface_commandBodyBackground_description {
            get {
                return ResourceManager.GetString("settings.userinterface.commandBodyBackground.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фоновое выделение команд.
        /// </summary>
        internal static string settings_userinterface_commandBodyBackground_title {
            get {
                return ResourceManager.GetString("settings.userinterface.commandBodyBackground.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки подсветки синтаксиса и фонового выделения строк в протоколе выполнения..
        /// </summary>
        internal static string settings_userinterface_highlightsGroup_description {
            get {
                return ResourceManager.GetString("settings.userinterface.highlightsGroup.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подсветка и цвета протокола.
        /// </summary>
        internal static string settings_userinterface_highlightsGroup_title {
            get {
                return ResourceManager.GetString("settings.userinterface.highlightsGroup.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык интерфейса, на котором будут отображаться надписи и сообщения..
        /// </summary>
        internal static string settings_userinterface_language_description {
            get {
                return ResourceManager.GetString("settings.userinterface.language.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string settings_userinterface_language_title {
            get {
                return ResourceManager.GetString("settings.userinterface.language.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интерфейс.
        /// </summary>
        internal static string settings_userinterface_section_title {
            get {
                return ResourceManager.GetString("settings.userinterface.section.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает или отключает подсветку синтаксиса в редакторе протокола..
        /// </summary>
        internal static string settings_userinterface_syntaxHighlighting_description {
            get {
                return ResourceManager.GetString("settings.userinterface.syntaxHighlighting.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подсветка синтаксиса.
        /// </summary>
        internal static string settings_userinterface_syntaxHighlighting_title {
            get {
                return ResourceManager.GetString("settings.userinterface.syntaxHighlighting.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите тему оформления интерфейса, которая будет использоваться в приложении..
        /// </summary>
        internal static string settings_userinterface_theme_description {
            get {
                return ResourceManager.GetString("settings.userinterface.theme.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема приложения.
        /// </summary>
        internal static string settings_userinterface_theme_title {
            get {
                return ResourceManager.GetString("settings.userinterface.theme.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заменяет текстовые пункты верхнего меню на иконки..
        /// </summary>
        internal static string settings_userinterface_topMenuIcons_description {
            get {
                return ResourceManager.GetString("settings.userinterface.topMenuIcons.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иконки в верхнем меню.
        /// </summary>
        internal static string settings_userinterface_topMenuIcons_title {
            get {
                return ResourceManager.GetString("settings.userinterface.topMenuIcons.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться к исходному файлу.
        /// </summary>
        internal static string translator_editor_tooltip_back {
            get {
                return ResourceManager.GetString("translator.editor.tooltip.back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить странслированный файл в архив.
        /// </summary>
        internal static string translator_editor_tooltip_save_archive {
            get {
                return ResourceManager.GetString("translator.editor.tooltip.save.archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить исходный файл.
        /// </summary>
        internal static string translator_editor_tooltip_save_source {
            get {
                return ResourceManager.GetString("translator.editor.tooltip.save.source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ,сек..
        /// </summary>
        internal static string unit_seconds_suffix {
            get {
                return ResourceManager.GetString("unit.seconds.suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ,В..
        /// </summary>
        internal static string unit_volts_suffix {
            get {
                return ResourceManager.GetString("unit.volts.suffix", resourceCulture);
            }
        }
    }
}
