// <auto-generated />
using DataBaseConfiguration.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseConfiguration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401122627_AddRolePasswords")]
    partial class AddRolePasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Ask.Core.Shared.DTO.Executor.MeasurementError.MeasurementErrorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("MeasurementErrors");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Executor.MeasurementError.MeasurementErrorRangeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<int>("MeasurementErrorEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<double>("NumericError")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentageError")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementErrorEntityId", "MinValue", "MaxValue")
                        .IsUnique();

                    b.ToTable("MeasurementErrorRanges");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Devices.BreakdownTesterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IRMinVoltage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PiMaxVoltage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiMaxVoltage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BreakdownTesters");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Devices.ChassisManagerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChassisManagers");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Devices.FastMeterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxContinuityResistance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FastMeters");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Devices.PowerSourceModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResistanceCalibrationJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PowerSourceModules");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Devices.RackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rack");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Devices.RelaySwitchModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberRack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SwitchCapacitance")
                        .HasColumnType("REAL");

                    b.Property<double>("SwitchResistance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RelaySwitchModules");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Devices.SwitchingDeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SwitchingDevices");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Devices.UninterruptiblePowerSupplyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResolvedDevicePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UninterruptiblePowerSupplies");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Settings.DeviceDisplaySettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowConnectionInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDeviceExecutionParameters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowIntermediateMeasurementResults")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMachineAddresses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMeasurementResults")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeviceDisplaySettings");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Settings.RolePasswordModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Role")
                        .IsUnique();

                    b.ToTable("RolePasswords");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Settings.SettingsExecutionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IdleModeExecution")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsErrorSimulationMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StepByStepMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopOnError")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Execution");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Settings.SettingsProtocolModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPrintProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSaveProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CleanTextErrorsProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CleanTextProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisplayOperationTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorTextProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GenerateProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDetailedProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDeviceInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowHeaderInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowProtocolInSoftware")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SettingsProtocol");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.Settings.UserInterfaceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseChainPointBodyBackgroundHighlighting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCommandBodyBackgroundHighlighting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSyntaxHighlighting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseTopMenuIcons")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserInterface");
                });

            modelBuilder.Entity("Ask.Core.Shared.Entity.UI.FileHotkeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyCombination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileHotkeys");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Executor.MeasurementError.MeasurementErrorRangeEntity", b =>
                {
                    b.HasOne("Ask.Core.Shared.DTO.Executor.MeasurementError.MeasurementErrorEntity", "MeasurementErrorEntity")
                        .WithMany("Ranges")
                        .HasForeignKey("MeasurementErrorEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementErrorEntity");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Executor.MeasurementError.MeasurementErrorEntity", b =>
                {
                    b.Navigation("Ranges");
                });
#pragma warning restore 612, 618
        }
    }
}
