using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace UI.Controls.AdminPanel
{
  /// <summary>
  /// Логика взаимодействия для DatabaseTableView.xaml
  /// </summary>
  public partial class DatabaseTableView : UserControl
  {
    private IList? _rows;

    public DatabaseTableView()
    {
      InitializeComponent();
    }

    public void SetData(string tableName, IList rows)
    {
      TableTitle.Text = tableName;
      RowCount.Text = $"Записей: {rows.Count}";
      _rows = rows;
      Grid.ItemsSource = rows;
    }

    private void Grid_AutoGeneratedColumns(object sender, EventArgs e)
    {
      ApplyColumnSizing();
      ApplyTextColumnStyle();
      HideEmptyColumns();
    }

    private void ApplyColumnSizing()
    {
      foreach (var column in Grid.Columns)
      {
        column.Width = new DataGridLength(1, DataGridLengthUnitType.Auto);
        column.MinWidth = 140;
        column.MaxWidth = 420;
      }
    }

    private void ApplyTextColumnStyle()
    {
      if (Grid.TryFindResource("AdminDbDataGridTextStyle") is not Style textStyle)
      {
        return;
      }

      foreach (var column in Grid.Columns.OfType<DataGridTextColumn>())
      {
        column.ElementStyle = textStyle;
      }
    }

    private void HideEmptyColumns()
    {
      if (_rows == null || _rows.Count == 0)
      {
        return;
      }

      foreach (var column in Grid.Columns.OfType<DataGridBoundColumn>())
      {
        var path = GetBindingPath(column);
        if (string.IsNullOrWhiteSpace(path))
        {
          continue;
        }

        if (!ColumnHasData(path))
        {
          column.Visibility = Visibility.Collapsed;
        }
      }
    }

    private static string? GetBindingPath(DataGridBoundColumn column)
    {
      if (column.Binding is Binding binding)
      {
        return binding.Path?.Path;
      }

      return null;
    }

    private bool ColumnHasData(string path)
    {
      foreach (var row in _rows!.Cast<object>())
      {
        if (row == null)
        {
          continue;
        }

        var value = GetPropertyValue(row, path);
        if (HasMeaningfulValue(value))
        {
          return true;
        }
      }

      return false;
    }

    private static bool HasMeaningfulValue(object? value)
    {
      if (value == null || value == DBNull.Value)
      {
        return false;
      }

      if (value is string text)
      {
        return !string.IsNullOrWhiteSpace(text);
      }

      return true;
    }

    private static object? GetPropertyValue(object row, string path)
    {
      var current = row;

      foreach (var segment in path.Split('.'))
      {
        if (current == null)
        {
          return null;
        }

        var segmentName = segment;
        if (segmentName.StartsWith("[") && segmentName.EndsWith("]"))
        {
          segmentName = segmentName.Trim('[', ']');
        }

        var descriptor = TypeDescriptor.GetProperties(current)[segmentName];
        if (descriptor != null)
        {
          current = descriptor.GetValue(current);
          continue;
        }

        var property = current.GetType().GetProperty(segmentName);
        if (property == null)
        {
          return null;
        }

        current = property.GetValue(current);
      }

      return current;
    }
  }
}
}
