//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Админ.
        /// </summary>
        internal static string menu_admin {
            get {
                return ResourceManager.GetString("menu.admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Погрешность.
        /// </summary>
        internal static string menu_admin_error {
            get {
                return ResourceManager.GetString("menu.admin.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление.
        /// </summary>
        internal static string menu_admin_management {
            get {
                return ResourceManager.GetString("menu.admin.management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USB.
        /// </summary>
        internal static string menu_admin_usb {
            get {
                return ResourceManager.GetString("menu.admin.usb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение.
        /// </summary>
        internal static string menu_execution {
            get {
                return ResourceManager.GetString("menu.execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трансляции.
        /// </summary>
        internal static string menu_execution_build {
            get {
                return ResourceManager.GetString("menu.execution.build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск.
        /// </summary>
        internal static string menu_execution_run {
            get {
                return ResourceManager.GetString("menu.execution.run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        internal static string menu_file {
            get {
                return ResourceManager.GetString("menu.file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архив.
        /// </summary>
        internal static string menu_file_archive {
            get {
                return ResourceManager.GetString("menu.file.archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сравнить.
        /// </summary>
        internal static string menu_file_compare {
            get {
                return ResourceManager.GetString("menu.file.compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string menu_file_exit {
            get {
                return ResourceManager.GetString("menu.file.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        internal static string menu_file_new {
            get {
                return ResourceManager.GetString("menu.file.new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        internal static string menu_file_open {
            get {
                return ResourceManager.GetString("menu.file.open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть папку в проводнике.
        /// </summary>
        internal static string menu_file_openfolder {
            get {
                return ResourceManager.GetString("menu.file.openfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать.
        /// </summary>
        internal static string menu_file_print {
            get {
                return ResourceManager.GetString("menu.file.print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string menu_file_save {
            get {
                return ResourceManager.GetString("menu.file.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить как....
        /// </summary>
        internal static string menu_file_saveas {
            get {
                return ResourceManager.GetString("menu.file.saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        internal static string menu_file_search {
            get {
                return ResourceManager.GetString("menu.file.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        internal static string menu_help {
            get {
                return ResourceManager.GetString("menu.help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string menu_settings {
            get {
                return ResourceManager.GetString("menu.settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация.
        /// </summary>
        internal static string menu_settings_config {
            get {
                return ResourceManager.GetString("menu.settings.config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение.
        /// </summary>
        internal static string menu_settings_execution {
            get {
                return ResourceManager.GetString("menu.settings.execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол.
        /// </summary>
        internal static string menu_settings_protocol {
            get {
                return ResourceManager.GetString("menu.settings.protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Испытания.
        /// </summary>
        internal static string menu_test {
            get {
                return ResourceManager.GetString("menu.test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метрология.
        /// </summary>
        internal static string menu_test_metrology {
            get {
                return ResourceManager.GetString("menu.test.metrology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим СИ.
        /// </summary>
        internal static string menu_test_metrology_ci {
            get {
                return ResourceManager.GetString("menu.test.metrology.ci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ИЕ.
        /// </summary>
        internal static string menu_test_metrology_ie {
            get {
                return ResourceManager.GetString("menu.test.metrology.ie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим КН (переменный).
        /// </summary>
        internal static string menu_test_metrology_knacw {
            get {
                return ResourceManager.GetString("menu.test.metrology.knacw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим КН (постоянный).
        /// </summary>
        internal static string menu_test_metrology_kndcw {
            get {
                return ResourceManager.GetString("menu.test.metrology.kndcw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим КС.
        /// </summary>
        internal static string menu_test_metrology_ks {
            get {
                return ResourceManager.GetString("menu.test.metrology.ks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ПИ (переменный).
        /// </summary>
        internal static string menu_test_metrology_piacw {
            get {
                return ResourceManager.GetString("menu.test.metrology.piacw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ПИ (постоянный).
        /// </summary>
        internal static string menu_test_metrology_pidcw {
            get {
                return ResourceManager.GetString("menu.test.metrology.pidcw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ПР.
        /// </summary>
        internal static string menu_test_metrology_pr {
            get {
                return ResourceManager.GetString("menu.test.metrology.pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим ПР Т.
        /// </summary>
        internal static string menu_test_metrology_prt {
            get {
                return ResourceManager.GetString("menu.test.metrology.prt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самоконтроль.
        /// </summary>
        internal static string menu_test_selfcontrol {
            get {
                return ResourceManager.GetString("menu.test.selfcontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модуль.
        /// </summary>
        internal static string menu_test_selfcontrol_module {
            get {
                return ResourceManager.GetString("menu.test.selfcontrol.module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тесты.
        /// </summary>
        internal static string menu_test_tests {
            get {
                return ResourceManager.GetString("menu.test.tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест СИ.
        /// </summary>
        internal static string menu_test_tests_ci {
            get {
                return ResourceManager.GetString("menu.test.tests.ci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Групповой метод.
        /// </summary>
        internal static string menu_test_tests_ci_group {
            get {
                return ResourceManager.GetString("menu.test.tests.ci.group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод узла.
        /// </summary>
        internal static string menu_test_tests_ci_node {
            get {
                return ResourceManager.GetString("menu.test.tests.ci.node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перекрёстный тест(МКР).
        /// </summary>
        internal static string menu_test_tests_cross_mkr {
            get {
                return ResourceManager.GetString("menu.test.tests.cross.mkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест ПИ на переменном токе.
        /// </summary>
        internal static string menu_test_tests_piacw {
            get {
                return ResourceManager.GetString("menu.test.tests.piacw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Групповой метод.
        /// </summary>
        internal static string menu_test_tests_piacw_group {
            get {
                return ResourceManager.GetString("menu.test.tests.piacw.group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод узла.
        /// </summary>
        internal static string menu_test_tests_piacw_node {
            get {
                return ResourceManager.GetString("menu.test.tests.piacw.node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест ПИ на постоянном токе.
        /// </summary>
        internal static string menu_test_tests_pidcw {
            get {
                return ResourceManager.GetString("menu.test.tests.pidcw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Групповой метод.
        /// </summary>
        internal static string menu_test_tests_pidcw_group {
            get {
                return ResourceManager.GetString("menu.test.tests.pidcw.group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод узла.
        /// </summary>
        internal static string menu_test_tests_pidcw_node {
            get {
                return ResourceManager.GetString("menu.test.tests.pidcw.node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конечная точка a.b.c.
        /// </summary>
        internal static string point_finalPoint {
            get {
                return ResourceManager.GetString("point.finalPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальная точка a.b.c.
        /// </summary>
        internal static string point_startingPoint {
            get {
                return ResourceManager.GetString("point.startingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Административная панель.
        /// </summary>
        internal static string settings_execution_admin {
            get {
                return ResourceManager.GetString("settings.execution.admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отладка ошибок выполнения .
        /// </summary>
        internal static string settings_execution_admin_debuggingError {
            get {
                return ResourceManager.GetString("settings.execution.admin.debuggingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение режимов.
        /// </summary>
        internal static string settings_execution_executionModes {
            get {
                return ResourceManager.GetString("settings.execution.executionModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пошаговый режим.
        /// </summary>
        internal static string settings_execution_executionModes_stepByStepMode {
            get {
                return ResourceManager.GetString("settings.execution.executionModes.stepByStepMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановка по ошибке.
        /// </summary>
        internal static string settings_execution_executionModes_stopOnError {
            get {
                return ResourceManager.GetString("settings.execution.executionModes.stopOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Холостой режим.
        /// </summary>
        internal static string settings_execution_idleMode {
            get {
                return ResourceManager.GetString("settings.execution.idleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение с ошибками.
        /// </summary>
        internal static string settings_execution_idleMode_errSimulation {
            get {
                return ResourceManager.GetString("settings.execution.idleMode.errSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Холостой режим выполнения.
        /// </summary>
        internal static string settings_execution_idleMode_runMode {
            get {
                return ResourceManager.GetString("settings.execution.idleMode.runMode", resourceCulture);
            }
        }
    }
}
