log4cpp.rootCategory=WARN, rootAppender

log4cpp.appender.rootAppender=RollingFileAppender
log4cpp.appender.rootAppender.fileName=${PROGRAMDATA}/Keysight/Keysight IO Libraries/iols.log
log4cpp.appender.rootAppender.maxFileSize=2097152
log4cpp.appender.rootAppender.maxBackupIndex=50
log4cpp.appender.rootAppender.layout=PatternLayout
log4cpp.appender.rootAppender.layout.ConversionPattern=%d	[%p] - %m%n