namespace Ask.DataBase.Provider.Services.Devices;

/// <summary>
/// Содержит SQL-описание хранилища legacy-профилей аппаратуры АСК-МКИ.
/// </summary>
internal static class LegacyMkiHardwareProfileStorageSql
{
  /// <summary>
  /// Возвращает имя таблицы legacy-профилей аппаратуры АСК-МКИ.
  /// </summary>
  public const string TableName = "LegacyMkiHardwareProfiles";

  /// <summary>
  /// Возвращает SQL-команду создания таблицы legacy-профилей.
  /// </summary>
  public const string CreateTableSql =
    """
    CREATE TABLE IF NOT EXISTS "LegacyMkiHardwareProfiles" (
      "Id" INTEGER NOT NULL CONSTRAINT "PK_LegacyMkiHardwareProfiles" PRIMARY KEY AUTOINCREMENT,
      "NumberChassis" INTEGER NOT NULL,
      "ProfileKind" INTEGER NOT NULL,
      "UpdatedAtUtc" TEXT NOT NULL,
      "Nas" INTEGER NOT NULL,
      "DvAcp" INTEGER NOT NULL,
      "DvV7" INTEGER NOT NULL,
      "EtGui4" INTEGER NOT NULL,
      "SkIs" BLOB NOT NULL,
      "SkBkBeg" BLOB NOT NULL,
      "SkBkEnd" BLOB NOT NULL,
      "GuiType" BLOB NOT NULL,
      "GuiVoltStep" BLOB NOT NULL,
      "GuiAmperStep" BLOB NOT NULL,
      "GuiVoltMax" BLOB NOT NULL,
      "GuiAmperMax" BLOB NOT NULL,
      "KuGui4" INTEGER NOT NULL,
      "IsRos" INTEGER NOT NULL,
      "GomCmt" REAL NOT NULL,
      "TyPpu" INTEGER NOT NULL,
      "PkiUmax" INTEGER NOT NULL,
      "AcpTmr" INTEGER NOT NULL,
      "NAcpMaMax" INTEGER NOT NULL,
      "IsPki" INTEGER NOT NULL,
      "Comx4Com1" INTEGER NOT NULL,
      "BbSpr" INTEGER NOT NULL,
      "LcIs" INTEGER NOT NULL,
      "RbusBb" REAL NOT NULL,
      "PkiExtMo" INTEGER NOT NULL,
      "AcpIs0_3V" INTEGER NOT NULL,
      "DivGatBk" INTEGER NOT NULL,
      "UmaxEk" REAL NOT NULL,
      "EkFull" INTEGER NOT NULL,
      "UmaxSiEkFull" INTEGER NOT NULL,
      "UmaxPiEkFull" INTEGER NOT NULL,
      "CalcPgr" INTEGER NOT NULL,
      "HardwareConfigReserved" BLOB NOT NULL,
      "Res1" INTEGER NOT NULL,
      "IsTstUpki" INTEGER NOT NULL,
      "U220" INTEGER NOT NULL,
      "PkiAkomDiv" BLOB NOT NULL,
      "RwirAdc" REAL NOT NULL,
      "PkiKomTst" BLOB NOT NULL,
      "PpuKmul" REAL NOT NULL,
      "UacpR" REAL NOT NULL,
      "Uv7R" REAL NOT NULL,
      "Net" INTEGER NOT NULL,
      "BeepOff" INTEGER NOT NULL,
      "Meas2" INTEGER NOT NULL,
      "RwirV7" REAL NOT NULL,
      "Rgui4" REAL NOT NULL,
      "DIGui4mA" REAL NOT NULL,
      "KopAddr" INTEGER NOT NULL,
      "KmulKi" REAL NOT NULL,
      "LocErrSob" INTEGER NOT NULL,
      "ShortSsRt" INTEGER NOT NULL,
      "PkiAVolt" BLOB NOT NULL,
      "UseWait" INTEGER NOT NULL,
      "ReioVm" INTEGER NOT NULL,
      "PortSku" BLOB NOT NULL,
      "PortVm" BLOB NOT NULL,
      "PortFs" BLOB NOT NULL,
      "QMeasC" INTEGER NOT NULL,
      "OutUpi" INTEGER NOT NULL,
      "MksAcpTmr" INTEGER NOT NULL,
      "UsbAddrVm" TEXT NOT NULL,
      "TdobTdo" REAL NOT NULL,
      "TdobTi" REAL NOT NULL,
      "CcorrectPf" INTEGER NOT NULL,
      "ReioGui3" INTEGER NOT NULL,
      "PortGui3" BLOB NOT NULL,
      "HardwareAuxReserved" BLOB NOT NULL,
      "SkPwr" INTEGER NOT NULL,
      "BkBus" INTEGER NOT NULL,
      "EkRk" INTEGER NOT NULL,
      "PtEk" INTEGER NOT NULL,
      "PtRk" INTEGER NOT NULL,
      "EpPwr" INTEGER NOT NULL,
      "KzSh" INTEGER NOT NULL,
      "GuiPwr" INTEGER NOT NULL,
      "Gui4Mod" INTEGER NOT NULL,
      "GuiGat" INTEGER NOT NULL,
      "V734Mod" INTEGER NOT NULL,
      "V753Mod" INTEGER NOT NULL,
      "V765Mod" INTEGER NOT NULL,
      "V7Gat" INTEGER NOT NULL,
      "AcpMod" INTEGER NOT NULL,
      "AcpGat" INTEGER NOT NULL,
      "PkiPwr" INTEGER NOT NULL,
      "PkiMod" INTEGER NOT NULL,
      "PpuPwr" INTEGER NOT NULL,
      "PpuMod" INTEGER NOT NULL,
      "KoPwr" INTEGER NOT NULL,
      "EpBef" INTEGER NOT NULL,
      "V7Bef" INTEGER NOT NULL,
      "AcpBef" INTEGER NOT NULL,
      "PkiBef" INTEGER NOT NULL,
      "PpuBef" INTEGER NOT NULL,
      "V753RunR" INTEGER NOT NULL,
      "V753RunU" INTEGER NOT NULL,
      "V753RunV" INTEGER NOT NULL,
      "V765RunR" INTEGER NOT NULL,
      "V765RunU" INTEGER NOT NULL,
      "V765RunUv" INTEGER NOT NULL,
      "Gui3Mod" INTEGER NOT NULL,
      "Reserv1" BLOB NOT NULL,
      "GuiRst" INTEGER NOT NULL,
      "LcBef" INTEGER NOT NULL,
      "PpuAftPusk" INTEGER NOT NULL,
      "TMeasUppuMin" INTEGER NOT NULL,
      "TimingReserved" BLOB NOT NULL,
      "Password0" TEXT NOT NULL,
      "Password1" TEXT NOT NULL
    );
    """;

  /// <summary>
  /// Возвращает SQL-команду создания уникального индекса legacy-профилей.
  /// </summary>
  public const string CreateIndexSql =
    """
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_LegacyMkiHardwareProfiles_NumberChassis_ProfileKind"
    ON "LegacyMkiHardwareProfiles" ("NumberChassis", "ProfileKind");
    """;

  /// <summary>
  /// Возвращает определения всех колонок, которые должны быть в таблице legacy-профилей.
  /// </summary>
  public static IReadOnlyDictionary<string, string> Columns { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
  {
    ["NumberChassis"] = "INTEGER NOT NULL DEFAULT 0",
    ["ProfileKind"] = "INTEGER NOT NULL DEFAULT 0",
    ["UpdatedAtUtc"] = "TEXT NOT NULL DEFAULT ''",
    ["Nas"] = "INTEGER NOT NULL DEFAULT 0",
    ["DvAcp"] = "INTEGER NOT NULL DEFAULT 0",
    ["DvV7"] = "INTEGER NOT NULL DEFAULT 0",
    ["EtGui4"] = "INTEGER NOT NULL DEFAULT 0",
    ["SkIs"] = "BLOB NOT NULL DEFAULT X''",
    ["SkBkBeg"] = "BLOB NOT NULL DEFAULT X''",
    ["SkBkEnd"] = "BLOB NOT NULL DEFAULT X''",
    ["GuiType"] = "BLOB NOT NULL DEFAULT X''",
    ["GuiVoltStep"] = "BLOB NOT NULL DEFAULT X''",
    ["GuiAmperStep"] = "BLOB NOT NULL DEFAULT X''",
    ["GuiVoltMax"] = "BLOB NOT NULL DEFAULT X''",
    ["GuiAmperMax"] = "BLOB NOT NULL DEFAULT X''",
    ["KuGui4"] = "INTEGER NOT NULL DEFAULT 0",
    ["IsRos"] = "INTEGER NOT NULL DEFAULT 0",
    ["GomCmt"] = "REAL NOT NULL DEFAULT 0",
    ["TyPpu"] = "INTEGER NOT NULL DEFAULT 0",
    ["PkiUmax"] = "INTEGER NOT NULL DEFAULT 0",
    ["AcpTmr"] = "INTEGER NOT NULL DEFAULT 0",
    ["NAcpMaMax"] = "INTEGER NOT NULL DEFAULT 0",
    ["IsPki"] = "INTEGER NOT NULL DEFAULT 0",
    ["Comx4Com1"] = "INTEGER NOT NULL DEFAULT 0",
    ["BbSpr"] = "INTEGER NOT NULL DEFAULT 0",
    ["LcIs"] = "INTEGER NOT NULL DEFAULT 0",
    ["RbusBb"] = "REAL NOT NULL DEFAULT 0",
    ["PkiExtMo"] = "INTEGER NOT NULL DEFAULT 0",
    ["AcpIs0_3V"] = "INTEGER NOT NULL DEFAULT 0",
    ["DivGatBk"] = "INTEGER NOT NULL DEFAULT 0",
    ["UmaxEk"] = "REAL NOT NULL DEFAULT 0",
    ["EkFull"] = "INTEGER NOT NULL DEFAULT 0",
    ["UmaxSiEkFull"] = "INTEGER NOT NULL DEFAULT 0",
    ["UmaxPiEkFull"] = "INTEGER NOT NULL DEFAULT 0",
    ["CalcPgr"] = "INTEGER NOT NULL DEFAULT 0",
    ["HardwareConfigReserved"] = "BLOB NOT NULL DEFAULT X''",
    ["Res1"] = "INTEGER NOT NULL DEFAULT 0",
    ["IsTstUpki"] = "INTEGER NOT NULL DEFAULT 0",
    ["U220"] = "INTEGER NOT NULL DEFAULT 0",
    ["PkiAkomDiv"] = "BLOB NOT NULL DEFAULT X''",
    ["RwirAdc"] = "REAL NOT NULL DEFAULT 0",
    ["PkiKomTst"] = "BLOB NOT NULL DEFAULT X''",
    ["PpuKmul"] = "REAL NOT NULL DEFAULT 0",
    ["UacpR"] = "REAL NOT NULL DEFAULT 0",
    ["Uv7R"] = "REAL NOT NULL DEFAULT 0",
    ["Net"] = "INTEGER NOT NULL DEFAULT 0",
    ["BeepOff"] = "INTEGER NOT NULL DEFAULT 0",
    ["Meas2"] = "INTEGER NOT NULL DEFAULT 0",
    ["RwirV7"] = "REAL NOT NULL DEFAULT 0",
    ["Rgui4"] = "REAL NOT NULL DEFAULT 0",
    ["DIGui4mA"] = "REAL NOT NULL DEFAULT 0",
    ["KopAddr"] = "INTEGER NOT NULL DEFAULT 0",
    ["KmulKi"] = "REAL NOT NULL DEFAULT 0",
    ["LocErrSob"] = "INTEGER NOT NULL DEFAULT 0",
    ["ShortSsRt"] = "INTEGER NOT NULL DEFAULT 0",
    ["PkiAVolt"] = "BLOB NOT NULL DEFAULT X''",
    ["UseWait"] = "INTEGER NOT NULL DEFAULT 0",
    ["ReioVm"] = "INTEGER NOT NULL DEFAULT 0",
    ["PortSku"] = "BLOB NOT NULL DEFAULT X''",
    ["PortVm"] = "BLOB NOT NULL DEFAULT X''",
    ["PortFs"] = "BLOB NOT NULL DEFAULT X''",
    ["QMeasC"] = "INTEGER NOT NULL DEFAULT 0",
    ["OutUpi"] = "INTEGER NOT NULL DEFAULT 0",
    ["MksAcpTmr"] = "INTEGER NOT NULL DEFAULT 0",
    ["UsbAddrVm"] = "TEXT NOT NULL DEFAULT ''",
    ["TdobTdo"] = "REAL NOT NULL DEFAULT 0",
    ["TdobTi"] = "REAL NOT NULL DEFAULT 0",
    ["CcorrectPf"] = "INTEGER NOT NULL DEFAULT 0",
    ["ReioGui3"] = "INTEGER NOT NULL DEFAULT 0",
    ["PortGui3"] = "BLOB NOT NULL DEFAULT X''",
    ["HardwareAuxReserved"] = "BLOB NOT NULL DEFAULT X''",
    ["SkPwr"] = "INTEGER NOT NULL DEFAULT 0",
    ["BkBus"] = "INTEGER NOT NULL DEFAULT 0",
    ["EkRk"] = "INTEGER NOT NULL DEFAULT 0",
    ["PtEk"] = "INTEGER NOT NULL DEFAULT 0",
    ["PtRk"] = "INTEGER NOT NULL DEFAULT 0",
    ["EpPwr"] = "INTEGER NOT NULL DEFAULT 0",
    ["KzSh"] = "INTEGER NOT NULL DEFAULT 0",
    ["GuiPwr"] = "INTEGER NOT NULL DEFAULT 0",
    ["Gui4Mod"] = "INTEGER NOT NULL DEFAULT 0",
    ["GuiGat"] = "INTEGER NOT NULL DEFAULT 0",
    ["V734Mod"] = "INTEGER NOT NULL DEFAULT 0",
    ["V753Mod"] = "INTEGER NOT NULL DEFAULT 0",
    ["V765Mod"] = "INTEGER NOT NULL DEFAULT 0",
    ["V7Gat"] = "INTEGER NOT NULL DEFAULT 0",
    ["AcpMod"] = "INTEGER NOT NULL DEFAULT 0",
    ["AcpGat"] = "INTEGER NOT NULL DEFAULT 0",
    ["PkiPwr"] = "INTEGER NOT NULL DEFAULT 0",
    ["PkiMod"] = "INTEGER NOT NULL DEFAULT 0",
    ["PpuPwr"] = "INTEGER NOT NULL DEFAULT 0",
    ["PpuMod"] = "INTEGER NOT NULL DEFAULT 0",
    ["KoPwr"] = "INTEGER NOT NULL DEFAULT 0",
    ["EpBef"] = "INTEGER NOT NULL DEFAULT 0",
    ["V7Bef"] = "INTEGER NOT NULL DEFAULT 0",
    ["AcpBef"] = "INTEGER NOT NULL DEFAULT 0",
    ["PkiBef"] = "INTEGER NOT NULL DEFAULT 0",
    ["PpuBef"] = "INTEGER NOT NULL DEFAULT 0",
    ["V753RunR"] = "INTEGER NOT NULL DEFAULT 0",
    ["V753RunU"] = "INTEGER NOT NULL DEFAULT 0",
    ["V753RunV"] = "INTEGER NOT NULL DEFAULT 0",
    ["V765RunR"] = "INTEGER NOT NULL DEFAULT 0",
    ["V765RunU"] = "INTEGER NOT NULL DEFAULT 0",
    ["V765RunUv"] = "INTEGER NOT NULL DEFAULT 0",
    ["Gui3Mod"] = "INTEGER NOT NULL DEFAULT 0",
    ["Reserv1"] = "BLOB NOT NULL DEFAULT X''",
    ["GuiRst"] = "INTEGER NOT NULL DEFAULT 0",
    ["LcBef"] = "INTEGER NOT NULL DEFAULT 0",
    ["PpuAftPusk"] = "INTEGER NOT NULL DEFAULT 0",
    ["TMeasUppuMin"] = "INTEGER NOT NULL DEFAULT 0",
    ["TimingReserved"] = "BLOB NOT NULL DEFAULT X''",
    ["Password0"] = "TEXT NOT NULL DEFAULT ''",
    ["Password1"] = "TEXT NOT NULL DEFAULT ''"
  };
}
