// <auto-generated />
using System;
using Ask.DataBase.Provider.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ask.DataBase.Provider.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.Breakdown.BreakdownTesterDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcwMaxVoltage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DcwMaxVoltage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IRMinVoltage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiMaxVoltage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemInsulationResistanceGOhm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BreakdownTesters");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.ChassisManager.ChassisManagerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChassisManagers");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.ChassisManager.LegacyMkiHardwareProfileDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("AcpBef")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("AcpGat")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AcpIs0_3V")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("AcpMod")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AcpTmr")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BbSpr")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BeepOff")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("BkBus")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CalcPgr")
                        .HasColumnType("INTEGER");

                    b.Property<short>("CcorrectPf")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Comx4Com1")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DIGui4mA")
                        .HasColumnType("REAL");

                    b.Property<byte>("DivGatBk")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DvAcp")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DvV7")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("EkFull")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("EkRk")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("EpBef")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("EpPwr")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("EtGui4")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GomCmt")
                        .HasColumnType("REAL");

                    b.Property<ushort>("Gui3Mod")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Gui4Mod")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("GuiAmperMax")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("GuiAmperStep")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ushort>("GuiGat")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("GuiPwr")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("GuiRst")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("GuiType")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("GuiVoltMax")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("GuiVoltStep")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("HardwareAuxReserved")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("HardwareConfigReserved")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte>("IsPki")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("IsRos")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("IsTstUpki")
                        .HasColumnType("INTEGER");

                    b.Property<double>("KmulKi")
                        .HasColumnType("REAL");

                    b.Property<ushort>("KoPwr")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("KopAddr")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("KuGui4")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("KzSh")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("LcBef")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("LcIs")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("LocErrSob")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Meas2")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("MksAcpTmr")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NAcpMaMax")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Nas")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Net")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("OutUpi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password0")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PkiAVolt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PkiAkomDiv")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ushort>("PkiBef")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PkiExtMo")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PkiKomTst")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ushort>("PkiMod")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PkiPwr")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PkiUmax")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PortFs")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PortGui3")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PortSku")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PortVm")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ushort>("PpuAftPusk")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PpuBef")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PpuKmul")
                        .HasColumnType("REAL");

                    b.Property<ushort>("PpuMod")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PpuPwr")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ProfileKind")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PtEk")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PtRk")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("QMeasC")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RbusBb")
                        .HasColumnType("REAL");

                    b.Property<byte>("ReioGui3")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ReioVm")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Res1")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Reserv1")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<double>("Rgui4")
                        .HasColumnType("REAL");

                    b.Property<double>("RwirAdc")
                        .HasColumnType("REAL");

                    b.Property<double>("RwirV7")
                        .HasColumnType("REAL");

                    b.Property<byte>("ShortSsRt")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SkBkBeg")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SkBkEnd")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SkIs")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<ushort>("SkPwr")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("TMeasUppuMin")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TdobTdo")
                        .HasColumnType("REAL");

                    b.Property<double>("TdobTi")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("TimingReserved")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte>("TyPpu")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("U220")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UacpR")
                        .HasColumnType("REAL");

                    b.Property<double>("UmaxEk")
                        .HasColumnType("REAL");

                    b.Property<ushort>("UmaxPiEkFull")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("UmaxSiEkFull")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsbAddrVm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("UseWait")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Uv7R")
                        .HasColumnType("REAL");

                    b.Property<ushort>("V734Mod")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("V753Mod")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("V753RunR")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("V753RunU")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("V753RunV")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("V765Mod")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("V765RunR")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("V765RunU")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("V765RunUv")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("V7Bef")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("V7Gat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LegacyMkiHardwareProfiles");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.FastMeter.FastMeterDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AcwPpuDividerCoefficientPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DcwPpuDividerCoefficientPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContinuityResistance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FastMeters");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.PowerSourceModule.PowerSourceModuleDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResistanceCalibrationJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PowerSourceModules");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.Rack.RackDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rack");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.RelaySwitchModule.RelaySwitchModuleDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberRack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SwitchCapacitance")
                        .HasColumnType("REAL");

                    b.Property<double>("SwitchResistance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RelaySwitchModules");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.SwitchingDevice.SwitchingDeviceDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SwitchingDevices");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.UninterruptiblePowerSupply.UninterruptiblePowerSupplyDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastResolvedDevicePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UninterruptiblePowerSupplies");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Settings.DeviceDisplaySettingsDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowConnectionInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDeviceExecutionParameters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowIntermediateMeasurementResults")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMachineAddresses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMeasurementResults")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeviceDisplaySettings");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Settings.FileHotkeyDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyCombination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileHotkeys");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Settings.SettingsExecutionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisablePowerCheck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IdleModeExecution")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsErrorSimulationMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHardwareErrorSimulationMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LegacyCompatibilityMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StepByStepMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopOnError")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Execution");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Settings.SettingsProtocolDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPrintProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSaveProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CleanTextErrorsProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CleanTextProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisplayOperationTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorTextProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GenerateProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowCommandHeadersInProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDetailedProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDeviceInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowHeaderInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowProtocolInSoftware")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowTestStepMessagesInProtocol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SettingsProtocol");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Settings.UserInterfaceDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseChainPointBodyBackgroundHighlighting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCommandAutoCollapse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCommandBodyBackgroundHighlighting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSyntaxHighlighting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseTopMenuIcons")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserInterface");
                });
#pragma warning restore 612, 618
        }
    }
}
