// <auto-generated />
using Ask.DataBase.Provider.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ask.DataBase.Provider.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.Breakdown.BreakdownTesterDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IRMinVoltage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PiMaxVoltage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiMaxVoltage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BreakdownTesters");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.ChassisManager.ChassisManagerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChassisManagers");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.FastMeter.FastMeterDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContinuityResistance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FastMeters");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.PowerSourceModule.PowerSourceModuleDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResistanceCalibrationJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PowerSourceModules");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.Rack.RackDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rack");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.RelaySwitchModule.RelaySwitchModuleDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberRack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SwitchCapacitance")
                        .HasColumnType("REAL");

                    b.Property<double>("SwitchResistance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RelaySwitchModules");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.SwitchingDevice.SwitchingDeviceDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SwitchingDevices");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Devices.UninterruptiblePowerSupply.UninterruptiblePowerSupplyDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastResolvedDevicePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberChassis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UninterruptiblePowerSupplies");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Settings.DeviceDisplaySettingsDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowConnectionInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDeviceExecutionParameters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowIntermediateMeasurementResults")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMachineAddresses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMeasurementResults")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeviceDisplaySettings");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Settings.FileHotkeyDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyCombination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileHotkeys");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Settings.SettingsExecutionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IdleModeExecution")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsErrorSimulationMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LegacyCompatibilityMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StepByStepMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopOnError")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Execution");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Settings.SettingsProtocolDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoPrintProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSaveProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CleanTextErrorsProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CleanTextProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisplayOperationTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorTextProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GenerateProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowCommandHeadersInProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDetailedProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDeviceInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowHeaderInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowProtocolInSoftware")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowTestStepMessagesInProtocol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SettingsProtocol");
                });

            modelBuilder.Entity("Ask.Core.Shared.DTO.Settings.UserInterfaceDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseChainPointBodyBackgroundHighlighting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCommandAutoCollapse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCommandBodyBackgroundHighlighting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSyntaxHighlighting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseTopMenuIcons")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserInterface");
                });
#pragma warning restore 612, 618
        }
    }
}
