gateway-server-properties:
  port: "4201"
  cert: ""
  key: ""

instconf-server-properties:
  host: "127.0.0.1"
  port: "4203"
  hpp-port: "4500"
  handshake-timeout: 300

cert-server-properties:
  host: "localhost"
  port: "4202"

iolsconf-server-properties:
  host: "localhost"
  port: "4204"
  iols-port: "8180"
  handshake-timeout: 300

usermanagement-server-properties:
  host: "localhost"
  port: "4205"
  jwt-token:
    token-expire: 120
    expire-unit: "min"

backuprestore-server-properties:
  host: "localhost"
  port: "4206"

db-backup-restore:
  path: "${ProgramData}\\Keysight\\Secure Instrument Communication Expert\\db-backup"
  
logging:
  loglevel: "debug"
  maxsize: 25
  maxbackup: 10
  maxage: 14

